name: Android CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: assembleProdDebug
      run: ./gradlew :app:assembleProdDebug

    - name: Read version
      id: read_outputs
      shell: bash
      run: |
        fn=$(find app/build/outputs/apk -type f -name "*.apk" | head -n1)
        v=$(ls -l app/build/outputs/apk/prod/debug/ | grep apk | cut -f"13" -d" " | cut -f2 -d"-")
        echo "VERSION=$v" >> $GITHUB_OUTPUT
        echo "FILENAME=$fn" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files:
          ${{ steps.read_outputs.outputs.FILENAME }}

